DataDog/dd-sdk-flutter

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/example/pubspec.lock, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Pulls release prep changes into develop.
=> 🚀 Preparing for release of datadog_flutter_plugin 1.0.0-alpha.1

packages/datadog_flutter_plugin/README.md
Add documentation regarding data storage on Android and iOS
=> RUMM-1940 add documentation about data storage

packages/datadog_flutter_plugin/android/build.gradle
=> Update to version 1.12.0-beta1

packages/datadog_flutter_plugin/README.md
Prepares the Flutter SDK README for single sourcing into the Docs site with a doc review first.
Formatting borrowed from iOS Monitoring and Android Monitoring doc pages.
=> Flutter SDK Beta Documentation Edit

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/e2e_test_app/integration_test/test_utils.dart, packages/datadog_flutter_plugin/example/lib/main.dart, packages/datadog_flutter_plugin/integration_test_app/lib/auto_integration_scenarios/main.dart, packages/datadog_flutter_plugin/integration_test_app/lib/main.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/test/datadog_sdk_method_channel_test.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart
=> 💥 Make `site` a required configuration parameter.

README.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/lib/src/datadog_plugin.dart, packages/datadog_tracking_http_client/README.md, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client_plugin.dart, packages/datadog_tracking_http_client/pubspec.yaml
New `datadog_tracking_http_client` package needed documentation in the main repos
=> 📝 Add documentation for new tracking http client package.

packages/datadog_flutter_plugin/README.md, packages/datadog_tracking_http_client/README.md, tools/releaser/README.md
Grammar fixes requested on last merge to main in documentation
=> 📝 Grammar fixes to documentation

packages/datadog_tracking_http_client/example/android/app/build.gradle, packages/datadog_tracking_http_client/example/android/build.gradle, packages/datadog_tracking_http_client/example/android/gradle/wrapper/gradle-wrapper.properties
Requested from a previous PR -- update gradle plugin to 7.1.x on the tracking client example.
=> 🧹 Update gradle plugin on tracking client example.

packages/datadog_flutter_plugin/README.md
=> 📝 Fix broken pub link in documentation.

LICENSE-3rdparty.csv, bitrise.yml, tools/third_party_scanner/bin/third_party_scanner.dart
No new 3rd party dependencies, but needed to add these packages just in case.
=> 🔨 Add missing packages to 3rd party scanner.

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Prep release PR (develop side)
=> 🚀 Preparing for release of datadog_flutter_plugin 1.0.0-beta.1

packages/datadog_flutter_plugin/README.md, packages/datadog_tracking_http_client/README.md, tools/releaser/README.md
This pulls the documentation changes made in `main` back into `develop`
=> 📝 Pull documentation changes from main back into develop

packages/datadog_common_test/lib/datadog_common_test.dart, packages/datadog_common_test/lib/src/data_helpers.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/logs/logger_config_test.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/logs/logger_test.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/rum/rum_consent_test.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/rum/rum_monitor_test.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/test_utils.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/traces/traces_config_test.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/traces/traces_test.dart, packages/datadog_flutter_plugin/e2e_test_app/pubspec.lock, packages/datadog_flutter_plugin/e2e_test_app/pubspec.yaml, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_flutter_plugin/pubspec.yaml
The randomString and randomElement functions are likely to be useful across all packages for testing so better to move them into the common test utilities package.
=> ♻️ Move some data helpers into datadog_common_test

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/example/pubspec.lock, packages/datadog_flutter_plugin/pubspec.yaml
Mostly updating documentation, but also putting the repo into the state I want it to be for the new release process.
=> 📝 Prepare for release of beta.2

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/example/pubspec.lock, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/example/pubspec.lock, packages/datadog_tracking_http_client/pubspec.yaml
As part of the new release process, the `develop` branch will contain next version number currently in development. This bumps all currently in dev libraries to their next in development version.
This "next version" does not mean that's the actual next version that will come out, but will help keep deployed vs. development versions clearer.
=> 📝 Bump version post beta.2 release.

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/android/build.gradle
=> Update to version 1.13.0

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_tracking_http_client/README.md
Updating the Changelog for datadog_flutter_plugin with most recent changes.
Added more documentation around Flutter 2.10 support in datadog_tracking_http_client.
=> 📝 Update docs

.gitignore, bitrise.yml, packages/datadog_common_test/pubspec.yaml, packages/datadog_flutter_plugin/e2e_test_app/pubspec.yaml, packages/datadog_grpc_interceptor/pubspec.yaml, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/example/pubspec.yaml, packages/datadog_tracking_http_client/pubspec.yaml, tools/ci/Makefile, tools/ci/choose_workflows.py, tools/ci/src/ci_context.py, tools/ci/src/utils.py, tools/e2e_generator/pubspec.yaml, tools/releaser/pubspec.yaml, tools/third_party_scanner/pubspec.yaml
The datadog_flutter_plugin has a constraint of SDK 2.15.0 (Flutter 2.8.0). It should be safe to move this constraint to be at least in line with that.
Fixes #155
=> ⬇️ Lower SDK Constraint for datadog_tracking_http_client

packages/datadog_flutter_plugin/android/ndk_crash_reports/network_information
This file snuck in at some point. It should be in the .gitignore but somehow snuck into the repo.
=> 🧹 Remove unwanted file (already .gitignored)

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Updates Changelog and bumps the version for the next potential release
=> Preparing for release of datadog_flutter_plugin 1.0.0-beta.3

packages/datadog_flutter_plugin/CHANGELOG.md
Update the change log to add the relevant changes from the iOS 1.12 beta update. Also fix issue linking.
=> 📝 Add changes from iOS version bump to Changelog

packages/datadog_tracking_http_client/CHANGELOG.md
Added changes from 1.0.1-rc.1, added items for the current unreleased 1.1.0 version.
=> 📝 Updating changelog for datadog_tracking_http_client

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
This is a chore for updating versions post release
=> Update versions post release

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
=> 🔀 Merge rc.2 changes back to develop

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
=> 🔀 Changes from releasing v1.0.0 rc.3

packages/datadog_flutter_plugin/README.md
References to two links got mixed up in recent changes.
This fixes #221
=> 📝 Fix link references in documentation

README.md, packages/datadog_grpc_interceptor/CHANGELOG.md, packages/datadog_grpc_interceptor/README.md, packages/datadog_grpc_interceptor/pubspec.yaml
Updating all docs and bumping versions for release of the gRPC interceptor.
=> 📝 Docs and version updates

.github/CODEOWNERS, bitrise.yml, packages/datadog_common_test/analysis_options.yaml, packages/datadog_common_test/lib/src/decoders/rum_decoder.dart, packages/datadog_common_test/lib/src/mock_http_sever.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum.dart, packages/datadog_grpc_interceptor/analysis_options.yaml, packages/datadog_grpc_interceptor/lib/src/datadog_grpc_interceptor.dart, packages/datadog_grpc_interceptor/test/datadog_grpc_interceptor_test.dart, packages/datadog_tracking_http_client/analysis_options.yaml, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/pubspec.yaml, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
The grpc interceptor and shared debug helper libraries were missing stricter analysis options. Added them in and fixed warnings.
Also update CODEOWNERS so the documentation team owns all doc directories as well as docs.
=> 🧹 Add stricter analysis rules for sub-packages

packages/datadog_flutter_plugin/lib/src/rum/rum_gesture_detector.dart
Walking the element tree had an issue where we would walk elements completely obscured by a more foreground element, and report a tap for the wrong element
Instead of just walking the element tree, we run a "hitTest" against the listener render object, and look for matching render objects in the element tree, until we find one that was in the hit path and also should be reported to RUM.
=> ✨ Fix RumUserActionDetector

packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/android/build.gradle
Updating from version 1.14.0-beta2 to version 1.14.0: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.14.0-beta2...1.14.0)
=> Update to version 1.14.0

packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/doc/common_setup.md, packages/datadog_flutter_plugin/doc/log_collection.md, packages/datadog_flutter_plugin/doc/rum/advanced_configuration.md, packages/datadog_flutter_plugin/doc/rum/data_collected.md, packages/datadog_flutter_plugin/doc/rum/error_tracking.md, packages/datadog_flutter_plugin/doc/rum/mobile_vitals.md, packages/datadog_flutter_plugin/doc/rum/rum_collection.md, packages/datadog_flutter_plugin/doc/troubleshooting.md, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart
Get updated documentation to develop
=> 🔀 Merge main to develop

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
=> Chore: Update versions for release of v1.0.0

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/android/build.gradle
* Update Android DD SDK to 1.14.1
Co-authored-by: root <root@runner-gsjmqsk-project-1238-concurrent-0>
Co-authored-by: Jeff Ward <jeff.ward@datadoghq.com>
=> Cherry pick Android SDK Update to 1.0 Release

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
=> Bump version post v1.0.1 release

packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift
These fixes came from updating and running swiftlint.
=> 🧹 Swiftlint provided fixes

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/example/ios/Podfile.lock, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin_web.dart, packages/datadog_flutter_plugin/lib/src/datadog_sdk_method_channel.dart, packages/datadog_flutter_plugin/lib/src/datadog_sdk_platform_interface.dart, packages/datadog_flutter_plugin/test/datadog_sdk_method_channel_test.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart
This allows users to set additionally attributes on a user without having to reset their name, id or email.
Fixes #254
=> ✨ Add a method for setting adding user attributes

examples/native-hybrid-app/README.md, examples/native-hybrid-app/android/settings.gradle, examples/native-hybrid-app/ios/iOS Flutter Hybrid Example/AppDelegate.swift, examples/native-hybrid-app/ios/iOS Flutter Hybrid Example/FirstViewController.swift
Small change to have Android's add-to-app example pull from snapshots instead for the latest version of code, and changes from code review for the iOS example.
=> 💚 Minor fixes for add-to-app example scenario

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Update change logs and readmes, bump to next potential version.
=> 🧹 1.1.0 Release Chores

examples/native-hybrid-app/android/app/build.gradle, examples/native-hybrid-app/android/settings.gradle, packages/datadog_flutter_plugin/android/build.gradle, packages/datadog_flutter_plugin/android/datadog_version.toml, packages/datadog_flutter_plugin/android/settings.gradle, packages/datadog_flutter_plugin/e2e_test_app/android/settings.gradle, packages/datadog_flutter_plugin/example/android/app/build.gradle, packages/datadog_flutter_plugin/example/android/build.gradle, packages/datadog_flutter_plugin/example/android/settings.gradle, packages/datadog_flutter_plugin/integration_test_app/android/settings.gradle, packages/datadog_tracking_http_client/example/android/settings.gradle, tools/releaser/lib/gradle_util.dart, tools/releaser/lib/release_validator.dart
Cherry pick reverting the version catalog to 1.1.0 release branch
Fixes #277
=> 🔥 Revert version catalog

examples/native-hybrid-app/android/app/build.gradle, ignore_sr_snapshots.gradle, packages/datadog_flutter_plugin/android/build.gradle, packages/datadog_flutter_plugin/example/android/app/build.gradle, packages/datadog_flutter_plugin/integration_test_app/android/app/build.gradle
=> Ignore SR Snapshots from dependencies

packages/datadog_flutter_plugin/doc/rum/otel_support.md, packages/datadog_flutter_plugin/doc/troubleshooting.md
Add documentation on how to generate OTel and `traceparent` style headers.
Also add a bit of troubleshooting documentation.
=> 📝 Add docs for OTel header generation and ingestion

packages/datadog_flutter_plugin/example/lib/logging_screen.dart
Testing attaching errors to logs and realized we didn't have an example in the example app.
=> ✨ Add a log with an error to the example app

packages/datadog_flutter_plugin/doc/rum/otel_support.md
Removes an unnecessary space between OpenTelemetry (the product name) and changes one small sentence to be complete.
=> 📝 Minor documentation updates

examples/README.md, examples/native-hybrid-app/README.md, packages/datadog_flutter_plugin/integration_test_app/README.md, packages/datadog_tracking_http_client/README.md
These are requests for documentation updates made in the backport PR (#313). Better to pull them into `develop` instead.
=> 📝 Doc update suggestions from review

packages/datadog_flutter_plugin/CHANGELOG.md
Add relevant changes from the iOS / Android SDK updates to the core package CHANGELOG.
=> 📝 Update CHANGELOG with iOS / Android SDK updates

packages/datadog_flutter_plugin/android/build.gradle
This file doesn't get published to pub because it's not in the root, and is breaking client builds.
=> 💚 Remove the import of the SR ignore

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Changes related to shipping 1.2.0.
=> 🚀 Bump from release of 1.2.0

examples/native-hybrid-app/android/app/build.gradle, packages/datadog_flutter_plugin/android/build.gradle, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/e2e_test_app/ios/Podfile, packages/datadog_flutter_plugin/example/android/app/build.gradle, packages/datadog_flutter_plugin/example/ios/Podfile, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/integration_test_app/ios/Podfile, packages/datadog_flutter_plugin/integration_test_app/ios/Runner.xcodeproj/project.pbxproj, packages/datadog_flutter_plugin/integration_test_app/ios/Runner/Info.plist, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_tracking_http_client/example/ios/Podfile, packages/datadog_tracking_http_client/example/pubspec.lock, tools/third_party_scanner/pubspec.lock
Unpin iOS / Android versions to most recent develop.
=> ⬆️ Unpin Android / iOS versions

packages/datadog_flutter_plugin/doc/rum/otel_support.md
Applies a couple of minor updates to match the doc's team style.
Capitalization of HTTP and sentence capitalization for headers.
=> minor fixes

packages/datadog_flutter_plugin/CHANGELOG.md
Minor CHANGELOG  update from 1.2.1 release
=> 📝 Add CHANGELOG from 1.2.1 release

packages/datadog_flutter_plugin/doc/rum/rum_collection.md
Describes a new config set up option for automatically collecting user data.
[DOCS-4882](https://datadoghq.atlassian.net/browse/DOCS-4882), which is a part of [DOCS-4827](https://datadoghq.atlassian.net/browse/DOCS-4827).
[DOCS-4882]: https://datadoghq.atlassian.net/browse/DOCS-4882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-4827]: https://datadoghq.atlassian.net/browse/DOCS-4827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> new option

packages/datadog_flutter_plugin/doc/rum/advanced_configuration.md, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_tracking_http_client/example/pubspec.lock, tools/third_party_scanner/pubspec.lock
Documentation had an inconsistency asking users to look for a method on DdRum that was actually on DatadogSdk
Fixes #344
=> 📝 Minor doc fix for setUserInfo

packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/example/ios/Tests/DatadogConfigurationTests.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_tracking_http_client/example/pubspec.lock
Add support for ap1.datadoghq.com
=> ✨ Support ap1.datadoghq.com

packages/datadog_flutter_plugin/CHANGELOG.md
Add CHANGELOG for 1.2.2 back into develop.
=> 📝 Add CHANGELOG from 1.2.2 release

packages/datadog_flutter_plugin/README.md
Updates the screenshot for new Flutter applications because it was outdated.
Replaces the image.
=> Replace new application details images for RUM Flutter

packages/datadog_flutter_plugin/CHANGELOG.md
Add changelog items from point release.
=> 📝 Pull minor version changelog

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Bump versions for 1.3.2 release
=> 🚀 Bump versions from 1.3.2 release

packages/datadog_webview_tracking/CHANGELOG.md, packages/datadog_webview_tracking/example/pubspec.lock, packages/datadog_webview_tracking/lib/src/datadog_webview.dart, packages/datadog_webview_tracking/pubspec.yaml
There were some issues in files preventing publishing the webview plugin. This fixes them so it can be published.
=> 🧹 Fix files that are preventing publishing webview package.

packages/datadog_flutter_plugin/doc/rum/advanced_configuration.md, packages/datadog_flutter_plugin/doc/rum/error_tracking.md, packages/datadog_webview_tracking/example/pubspec.lock
Pull documentation changes made in main into develop
=> 🔀 Merge main into develop

packages/datadog_webview_tracking/CHANGELOG.md, packages/datadog_webview_tracking/pubspec.yaml
Update versions and docs from shipping datadog_webview_tracking 1.0.0
=> 🚀 Update versions from shipping datadog_webview_tracking 1.0.0

packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogRumPlugin.kt, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ContractHelpers.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogLogsPluginTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogRumPluginTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ReflectUtils.kt
We've accumulated some Kotlin warnings / lints that I wanted to cleanup. I've also refactored the giant switch statement to be one line per message received.
=> 🧹 Cleanup lints / warnings in Android project

packages/datadog_flutter_plugin/doc/rum/advanced_configuration.md
RumUserActionDetector has been available as part of the API for a while and was recently improved to have more functionality. Adding documentation on how to use it to the main docs site.
=> 📝 Add documentation on the RumUserActionDetector

packages/datadog_flutter_plugin/CHANGELOG.md
Actually going to ship with 1.19, not 1.18
=> 📝 Update iOS SDK version in changelog

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Maintenance PR to update versions for next potential release.
=> 🚀 Bump versions from 1.4 release

bitrise.yml, packages/datadog_flutter_plugin/example/pubspec.yaml, packages/datadog_flutter_plugin/integration_test_app/integration_test/logging_mapping_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/logging_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_error_reporting_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/rum_manual_error_reporting_scenario.dart, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/pubspec.lock
Crash fix needs to come into the 2.8 compatible line.
Also update build for this branch to be pinned at Flutter 2.10.5
=> 🔀 Cherry pick crash fix into 1.3.x line

packages/datadog_flutter_plugin/CHANGELOG.md
Missed one change to the main library, added additional information about the Flutter 3.3 upgrade and Flutter 3.10 compatibility.
=> 📝 Minor CHANGELOG additions

examples/native-hybrid-app/android/app/build.gradle, packages/datadog_flutter_plugin/android/build.gradle, packages/datadog_flutter_plugin/example/android/app/build.gradle, packages/datadog_webview_tracking/android/build.gradle
Update Android version pin to 1.19.2
=> ⬆️ Update Android pin to 1.19.2

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_tracking_http_client/CHANGELOG.md
=> 📝 CHANGELOG updates
