DataDog/dd-sdk-flutter

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogTracesPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogTracesPluginTest.kt, packages/datadog_flutter_plugin/ios/Classes/DatadogTracesPlugin.swift, packages/datadog_flutter_plugin/lib/src/datadog_tracking_http_client.dart, packages/datadog_flutter_plugin/lib/src/traces/ddtraces.dart, packages/datadog_flutter_plugin/lib/src/traces/ddtraces_method_channel.dart, packages/datadog_flutter_plugin/lib/src/traces/ddtraces_platform_interface.dart, packages/datadog_flutter_plugin/test/datadog_tracking_http_client_test.dart, packages/datadog_flutter_plugin/test/traces/ddtraces_method_channel_test.dart, packages/datadog_flutter_plugin/test/traces/ddtraces_test.dart
This prevents the spans from leaking native resources.
Added a `cancel` method to Spans that does nothing but remove the span from the map. Since we're not holding onto the span, GCs on the platforms should take care of cleaning them up.
=> 🐛 Cancel spans from the DatadogTracingHttpClient when RUM is enabled

tools/releaser/README.md, tools/releaser/bin/deployer.dart
Since depoyments are made after a merge of a PR on main, the commit message wasn't the "Preparing" commit message expected. So we no longer check for it, and instead rely on a package name argument.
Also added a change to add the change log for the version to the release body.
=> 👩‍💻 Fix the deploy script

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt
Native view tracking will start the MainActivity view and won't show the active Flutter view if a user starts a secondary Activity (like a chrome custom tab).
We may want to add native view tracking in as an option later (similar to RN).
=> 🐛 Disable native view tracking on android.

packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ContractHelpers.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogLogsPluginTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogRumPluginTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogTracesPluginTest.kt
Instead of depending on KType, use an enum in conjunction with a sealed class to support specific values. This is needed so that we can properly create a logger with a fixed key as part of the test.
This is in service to RUMM-2083
=> ♻️ Change Android contract testing to support values

bitrise.yml, tools/third_party_scanner/bin/third_party_scanner.dart
This will allow us to check licenses continuously instead of waiting until release.
Add a step to the bitrise build, and ignore references to the package itself when performing the third party scans.
=> 👩‍💻 Run third party scanner as part of CI

packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogRumPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogRumPluginTest.kt, packages/datadog_flutter_plugin/e2e_test_app/integration_test/rum/rum_monitor_test.dart, packages/datadog_flutter_plugin/example/ios/Tests/DatadogRumPluginTests.swift, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum/rum_manual_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/rum_manual_instrumentation_scenario.dart, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/lib/src/datadog_tracking_http_client.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_method_channel.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_platform_interface.dart, packages/datadog_flutter_plugin/test/datadog_tracking_http_client_test.dart, packages/datadog_flutter_plugin/test/rum/ddrum_method_channel_test.dart
On Android this was creating a Throwable that made it look like the SDK was the source of the error.
=> 🐛 Remove stack trace from resource loading errors

packages/datadog_tracking_http_client/pubspec.yaml, tools/releaser/lib/version_updater.dart
Packages that are not the core package do not need `version.dart` files. This file is only used.to set the version of the SDK during DdSdk initialization.
Additionally, add a direct dependency for tracking_http_client that was missing from the pubspec.
=> Fixes to support deploying tracking_http_client package

packages/datadog_tracking_http_client/CHANGELOG.md
Prepare datadog_tracking_http_client release.
=> 🚀 Preparing for release of datadog_tracking_http_client 1.0.0-alpha.1

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/e2e_test_app/pubspec.lock, packages/datadog_flutter_plugin/example/ios/Tests/DatadogConfigurationTests.swift, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_tracking_http_client/example/integration_test/tracking_http_client_test.dart
Instead of only holding firstPartyHosts on the Flutter side, send them to the Native SDKs during initialization, and make them readonly on the Flutter side.
This should help correctly classify first party resources on dashboards.
=> 🐛 Set firstPartyHosts on Native SDKs during initialization

bitrise.yml
Moving the flutter install (which is currently hosted on the bitrise site) into the script hosted in the repo.
This is so that we can install the beta channel for the datadog_tracking_http_client package release.
=> 👷 Move flutter install to repo hosted bitrise script

packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/datadog_internal.dart, packages/datadog_flutter_plugin/lib/src/rum/attributes.dart, packages/datadog_flutter_plugin/lib/src/traces/ddtraces.dart, packages/datadog_grpc_interceptor/analysis_options.yaml, packages/datadog_grpc_interceptor/test/datadog_grpc_interceptor_test.dart, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/example/integration_test/tracking_http_client_test.dart, packages/datadog_tracking_http_client/example/ios/Podfile.lock, packages/datadog_tracking_http_client/example/pubspec.lock, packages/datadog_tracking_http_client/example/pubspec.yaml, packages/datadog_tracking_http_client/lib/datadog_tracking_http_client.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/pubspec.yaml, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
This is a first step for removing the Tracer. Generate Span / Trace IDs on the Dart side and use those when sending resource to RUM.
Integration tests are passing but I need to check E2E in Shopist as well.
=> Remove tracing calls from DatadogTracingHttpClient

bitrise.yml, packages/datadog_grpc_interceptor/pubspec.yaml
Set the required Flutter version down to 2.16.1 on the gRPC plugin.
Install flutter version manually in the bitrise.yaml.  
Nightly e2e is currently failing because the version bitrise is installing is 2.16.1, where latest is 2.16.2, which is what the gRPC plugin was set to.
=> 💚Fix nightly e2e

packages/datadog_flutter_plugin/lib/src/traces/ddtraces.dart, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
For compatibility with systems that do not support unsigned 64-bit integers, some Datadog services only support 63-bit trace ids. Make sure we only send 63-bits.
Reduce the max value of the high bits to 31-bits, then shift into the high 32-bits.
=> 🐛 Fix TraceId to be a 63-bit integer.

packages/datadog_flutter_plugin/README.md, packages/datadog_tracking_http_client/README.md
Improve some of our documentation.
Add a missing semi-colon in the `datadog_tracking_http_client` README.
Add information about needing to set `firstPartyHosts` when using the tracking http client.
=> 📝 Minor adjustments to documentation

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs.dart
Since DdLogs is returned by calls to `createLogger` it makes sense to add it to the externally visible classes via an `export`.
Also added getting started documentation for logging as well as documented methods on DdLogs.
Fixes #121
=> 📝 Added DdLogs to externally visible classes

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/e2e_test_app/pubspec.lock, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs.dart, packages/datadog_flutter_plugin/test/logs/ddlogs_test.dart
Allow clients to specify what level of logging should be sent to Datadog. The `datadogReportingThreshold` parameter on logger configuration determines what level of logs should get sent to Datadog from that logger.
=> ✨Added `datadogReportingThreshold` to loggers

packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt
e2e tests were failing because "stop" wasn't being called during reinitialization between tests, which made it so that we couldn't reinitialize.
Apparently, internal methods are mangled with the package name. Adding that to the method name fixed stop not being called.
=> ✅ Fix nightly e2e by changing internal method signature

packages/datadog_common_test/pubspec.yaml, packages/datadog_flutter_plugin/e2e_test_app/pubspec.yaml, packages/datadog_grpc_interceptor/pubspec.yaml, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/example/pubspec.yaml
All pubspecs, other than datadog_tracking_http_client 1.0.1+ should allow versions of dart as low as 2.15 (Fluter 2.8). This was changed in the release for datadog_tracking_http_client 1.0.0-beta.2 and this brings those changes into mainline.
=> ⬇️ Cherry pick changes for lower required Dart SDK

packages/datadog_common_test/lib/src/decoders/rum_decoder.dart, packages/datadog_common_test/lib/src/request_log.dart, packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/example/ios/Tests/DatadogConfigurationTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/integration_test_app/integration_test/logging_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/main.dart, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/src/attributes.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart
The refactor that made the service name a global parameter of the configuration for Web broke passing that parameter to the native libraries. This fixes that issue and adds additional integration tests.
Fixes #159
=> 🐛 Fix serviceName being passed to native libraries

packages/datadog_flutter_plugin/docs/error_tracking.md
We've had some clients ask about the state of Native Crash Reporting and desymbolication. I'd like to add these docs and somewhere to point them to while we work on the simplified / unified solution.
=> 📝 Add error manual error tracking documentation

.gitignore, packages/datadog_flutter_plugin/android/build.gradle, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ReflectUtils.kt, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift
Because hot reload / hot restart can recall `main`, you can get multiple requests to initialize Datadog, and the warning we spit to the console can get annoying. This removes that warning if your initialization hasn't changed.
If your initialization has changed, this shows a warning.
This fixes #141
=> Don't attempt to reinitialize Datadog on hot-reload

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/android/build.gradle
Updating from version 1.13.0 to version 1.14.0-beta1: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.13.0...1.14.0-beta1)
=> Update to version 1.14.0-beta1

packages/datadog_flutter_plugin/README.md
corrected "configutation" to configuration
This change corrects the spelling of the word "configuration" in line 169.
=> fix simple typo in line 169

packages/datadog_common_test/lib/src/mock_http_sever.dart, packages/datadog_flutter_plugin/example/lib/crash_reporting_screen.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart
When running in simulators, writing sessions puts the files in a weird location. Printing to console is easier in these situations.
Also added a new Flutter error that is non-async, which results in a larger stack that goes further into Flutter's built-in libraries.
Also, added an extra regex test for firstPartyHosts.
=> 🔊 Adding logging messages to Mock Http server, add new example error

packages/datadog_flutter_plugin/README.md
We're starting to see some common issues when setting up the Flutter Datadog SDK, specifically around Cocoapods and Apple Silicon. Adding some troubleshooting tips for dealing with those as well as instructions for setting the SDK verbosity.
=> 📝 Add a few troubleshooting tips to the documentation.

.gitignore, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/example/ios/Tests/DatadogConfigurationTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin_web.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/datadog_sdk_method_channel.dart, packages/datadog_flutter_plugin/lib/src/datadog_sdk_platform_interface.dart, packages/datadog_flutter_plugin/lib/src/helpers.dart, packages/datadog_flutter_plugin/lib/src/internal_logger.dart, packages/datadog_flutter_plugin/lib/src/rum/rum_gesture_detector.dart, packages/datadog_flutter_plugin/test/datadog_sdk_method_channel_test.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart
If there's an issue in the Datadog SDK, we want to make sure we capture the error and fix it in the future. This attempts to capture as many errors as possible and send them to Datadog for analysis.
Also add a configuration option for the `telemetrySampleRate`.
Note, changes to the http_client will need to be brought into 1.0 branch.
The `wrap` function does most of the heavy lifting, sending errors to Datadog if any exception occurs other than those that are caused by serialization (which should be reported to the user).
=> ✨ Send telemetry to Datadog on errors

packages/datadog_common_test/lib/src/data_helpers.dart, packages/datadog_common_test/lib/src/decoders/rum_decoder.dart, packages/datadog_common_test/lib/src/decoders/span_decoder.dart, packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogRumPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogRumPluginTest.kt, packages/datadog_flutter_plugin/example/ios/Tests/DatadogRumPluginTests.swift, packages/datadog_flutter_plugin/example/lib/main.dart, packages/datadog_flutter_plugin/example/lib/rum_screen.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/rum_manual_instrumentation_scenario.dart, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_method_channel.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_platform_interface.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart, packages/datadog_flutter_plugin/lib/src/rum/rum_long_task_observer.dart, packages/datadog_flutter_plugin/test/rum/ddrum_method_channel_test.dart, packages/datadog_flutter_plugin/test/rum/ddrum_test.dart, packages/datadog_flutter_plugin/test/rum/rum_long_task_observer_test.dart
Report "long tasks," which are stalls of the main isolate than more a specific amount of time.
We create an observer that continuously adds a microtask to the end of the queue waiting for a short duration, then we check how much time has elapsed between each task. If more than `longTaskThreshold` seconds have elapsed, it will report a long task to the native code.
=> ✨ Long Task reporting

packages/datadog_flutter_plugin/example/ios/Runner/AppDelegate.swift, packages/datadog_flutter_plugin/example/ios/Tests/FlutterSdkAttibutesTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/Helpers/ContractHelpers.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogLogsPlugin.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogSdkPlugin.m, packages/datadog_flutter_plugin/ios/Classes/DdFlutterEncodable.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift
Originally I had my Xcode settings to 2 space indents, but that was conflicting trying to work on both the Flutter swift files and the iOS SDK, so I've switched it back to the 4 space default. This brings all swift files back in line with proper indentation.
=> 🧹 Reindent all swift files to XCode defaults

packages/datadog_flutter_plugin/test/rum/rum_long_task_observer_test.dart
The long task reporting in this test appears to vary slightly more than 20ms. Upping it to 50ms of leeway to hopefully make the test less flakey.
=> 💚 Fix flakey test in long task reporting

packages/datadog_flutter_plugin/example/pubspec.lock, packages/datadog_flutter_plugin/pubspec.yaml, packages/datadog_grpc_interceptor/pubspec.yaml, packages/datadog_tracking_http_client/example/pubspec.lock, packages/datadog_tracking_http_client/pubspec.yaml
Update versions in pubspecs to be rc.1 over beta.
This also updates datadog_tracking_http_client to use 1.1 over 1.0.1 for Dart 2.17
=> 🚀 Prep versions for RC

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/rum/rum_long_task_observer.dart
Pre-Flutter 3.0, WidgetsBinding.instance is optional, but in Flutter 3.0 it is not. Using it as a non-optional breaks users that are still working with Flutter 2
=> 🐛 Fix Pre-Flutter 3.0 analysis error

.gitignore, bitrise.yml, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/example/lib/main.dart, packages/datadog_tracking_http_client/example/pubspec.lock, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/pubspec.yaml, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
This sets up 1.0.1-rc.1 to be the Flutter 2.8 package, while 1.1.0-rc1 will be for Flutter 3+.
Also cherry pick telemetry changes into this package.
Note - CI for this package is likely to fail until the main plugin rc.1 is released.
=> 💥 Update datadog_tracking_http_client 1.0.x line for rc1

packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/README.md
Change the documentation to reflect that datadog_tracking_http_client 1.1.x is now the correct Flutter 3 version, and 1.0.x is for Flutter 2.8
=> 📝 Minor documentation fix for datadog_tracking_http_client

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/helpers.dart, packages/datadog_flutter_plugin/lib/src/rum/rum_long_task_observer.dart
Because WidgetsBinding.instance is optional in Flutter 2.x, we have to use `?.` to access it. However, in Flutter 3,  WidgetsBinding is now non-optional, and Flutter will give you a warning that your use of ?. is unnecessary, even when you put an `// ignore:` comment above it.
I added a method `ambiguate` that makes WidgetsBinding.instance back into to optional, which can then be used safely with `?.`. This is actually the recommend method from Flutter's release note on Flutter 3.0: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code
Fixes #203
=> 🐛 Fix WidgetsBinding.instance log spam

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogLogsPlugin.kt, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogRumPlugin.kt, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt
On Android, if you press the back button on the top of the view stack, the app backgrounds and detaches the Flutter engine. We would then clean up a lot of the Flutter -> Datadog glue. However, if the application was then reopened, Datadog would be in a weird state where native code was initialized and thus not re-setup any of the glue.
This changes it so the glue is always set up for all Datadog modules properly, and still cleaned up on a Flutter engine detach.
=> 🐛 Fix an issue backing out of an Android application

.vscode/settings.json, packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/e2e_test_app/pubspec.lock, packages/datadog_flutter_plugin/example/ios/Tests/DatadogConfigurationTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/DatadogRumPluginTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/example/pubspec.lock, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_tracking_http_client/example/pubspec.lock
This makes the behavior of the native long task reporter mostly consistent with the parameters passed to Flutter.
The one exception is that it appears Android always has long task reporting enabled, so regardless of the `detectLongTask` parameter, Android will detect long tasks at the provided threshold.
=> ✨ Forward long task parameters to native

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/example/ios/Tests/FlutterSdkAttibutesTests.swift, packages/datadog_flutter_plugin/ios/Classes/DdFlutterEncodable.swift
Flutter native lists from `dart:typed_data` were not being encoded properly, even though they are supported by the StandardMessageCodec, and therefore are interpreted as valid values by the Datadog plugin, until we go to encode them.
This fixes DdFlutterEncodable so that it recognizes FlutterStandardTypedData and encodes it properly.
In all cases, FlutterStandardTypedData is just a buffer (`Data`) with all of the values written to it using all platform conventions. Since we know the size and type, we can just use the unsafe pointer to create a types array, then immediately encode the resulting array.
=> Fix typed data encoding

packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/e2e_test_app/integration_test/test_utils.dart
E2E tests on Android were broken because of changes made around initialization to support the Flutter engine detaching. Calling "flushAndDeinitialize" was also detaching the rum and logs plugin, which was incorrect.
=> 💚 Fix e2e tests on Android

packages/datadog_grpc_interceptor/lib/src/datadog_grpc_interceptor.dart, packages/datadog_grpc_interceptor/test/datadog_grpc_interceptor_test.dart
Apparently to connect RUM resources properly to distributed tracing, we need to include a URL schema. For now, we're adding http / https to all calls that do not include a schema.
=> 🐛 Add a schema to the gRPC interceptor

packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/android/build.gradle
Updating from version 1.14.0-beta1 to version 1.14.0-beta2: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.14.0-beta1...1.14.0-beta2)
=> Update to version 1.14.0-beta2

packages/datadog_flutter_plugin/example/lib/crash_reporting_screen.dart
Flutter errors weren't being reported properly in the example app because of some lazy iterator evaluation. This fixes that.
=> 🐛 Fix an issue where the example app was not reporting errors correctly

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/e2e_test_app/pubspec.lock, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/example/pubspec.lock, packages/datadog_flutter_plugin/integration_test_app/lib/auto_integration_scenarios/main.dart, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs_web.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_tracking_http_client/example/lib/main.dart, packages/datadog_tracking_http_client/example/pubspec.lock
Custom endpoint was being used to set the logs and rum endpoint to the same endpoint, but we need capabilities to set each feature's endpoint separately.
=> 💥 Deprecate DdFlutterConfiguration.customEndpoint

packages/datadog_flutter_plugin/test/rum/navigation_observer_test.dart, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
I upgraded to Flutter 3.3 / Dart 2.18 and these showed as warnings. Most of these were private methods, moved to be local in tests. The underscores were nor necessary in that case.
=> 🚨 Fix Dart 2.18 warnings about local underscores

LICENSE-3rdparty.csv, packages/datadog_grpc_interceptor/pubspec.yaml
Protobuf is used in tests, so it needs to be listed as a dev dependency in order to publish to pub.
=> ⬆️ Update protobuf dependency in grpc_interceptor

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/integration_test_app/integration_test/common.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/main.dart, packages/datadog_flutter_plugin/lib/src/attributes.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart
When set, flavor get sent as the `variant` tag on both iOS and Android.
Fixes RUMM-2471
=> ✨ Add flavor / variant to configuration

packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt
User action tracking was enabled by default in Android and could cause issues when backgrounding and foregrounding the app.
Take advantage of a new method in Android to disable interaction tracking.
=> 🐛 Disable user action tracking in Android

tools/releaser/bin/releaser.dart
Current version of the releaser script assumes it only has to update pre-release versions. Now it needs to be able to update released versions.
This checks the branch we're releasing from. The default case (usually develop) is to update the minor version. On release branches, update the revision number. In all cases, if it's a pre-release version, update it as a pre-release.
=> 👷 Fix releaser to work on non-prerelease versions

packages/datadog_grpc_interceptor/pubspec.yaml, packages/datadog_tracking_http_client/pubspec.yaml
`datadog_grpc_interceptor` and `datadog_tracking_http_client` now depend on the stable releases of `datadog_flutter_plugin`
=> ⬆️ Update dependencies to depend on 1.0.0 of datadog_flutter_plugin

packages/datadog_tracking_http_client/pubspec.yaml
The package was incorrectly dependent on a prerelease version of Dart. Remove the "prerelease" portion of the dart dependency.
=> 🐛 Fix datadog_tracking_http_client Dart dependency

packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/pubspec.yaml
Update versions for next possible release of `datadog_tracking_http_client`
=> Chore: tracking_http_client: Update versions for release of v1.1.0

.vscode/launch.json, packages/datadog_flutter_plugin/example/pubspec.lock, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/auto_integration_scenarios/rum_auto_instrumentation_scenario.dart, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_tracking_http_client/example/pubspec.lock
The browser sends any stall on the main thread more than 50ms, and this is not configurable. So for our integration tests on Flutter we check that all are above 50ms instead of 100ms, and check that at least one is above the 200ms threshold.
Flutter web tests still have some flakiness that I can't pin down but this fixes the major issue.
=> ✅ Fix Flutter web tests, specifically around long tasks

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/android/build.gradle
Updating from version 1.14.0 to version 1.14.1: [diff](https://github.com/DataDog/dd-sdk-android/compare/1.14.0...1.14.1)
=> Update to version 1.14.1

packages/datadog_common_test/analysis_options.yaml, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/e2e_test_app/pubspec.lock, packages/datadog_flutter_plugin/lib/src/rum/navigation_observer.dart, packages/datadog_tracking_http_client/example/pubspec.lock
RouteAwareMixin is not able to get the class name of the Widget post deobfuscation, so I've added documentation to call that out.
=> 📝 Documentation changes for DatadogRouteAwareMixin

packages/datadog_flutter_plugin/e2e_test_app/ios/Podfile, packages/datadog_flutter_plugin/example/ios/Podfile, packages/datadog_flutter_plugin/example/ios/Podfile.lock, packages/datadog_flutter_plugin/integration_test_app/ios/Podfile, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_tracking_http_client/example/ios/Podfile, tools/releaser/bin/releaser.dart, tools/releaser/lib/cocoapod_util.dart, tools/releaser/lib/command.dart, tools/releaser/lib/release_validator.dart, tools/releaser/pubspec.lock, tools/releaser/pubspec.yaml
So that we can more quickly iterate on features in the Flutter SDK, we're going to start relying on iOS source directly instead of pinned Pod versions. This is done in the Podfiles of the individual projects, similarly to the `dependency_overrides` in the Flutter pubspec.yaml
As part of the release process, we remove the overrides from all the Podfiles and pin the spec to the most recently released version.
=> 👷 Set iOS podfiles to use git source directly

packages/datadog_flutter_plugin/ios/datadog_flutter_plugin.podspec
For the dependency resolution to work properly, we need the podspec to be very permissive with what versions it supports. For now, allow any 1.x version.
=> 👷 Modify in dev podspec to be looser with version numbers

examples/native-hybrid-app/README.md, examples/native-hybrid-app/flutter_module/lib/main.dart, examples/native-hybrid-app/flutter_module/lib/my_app.dart, examples/native-hybrid-app/flutter_module/pubspec.lock, examples/native-hybrid-app/flutter_module/pubspec.yaml, examples/native-hybrid-app/ios/Podfile, examples/native-hybrid-app/ios/Podfile.lock, packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/datadog_plugin.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/lib/datadog_tracking_http_client.dart
Additional configuration options are needed to support features that are implemented only in Dart / don't share information with Native code. This includes whether to perform longTask detection for Dart, and the long task threshold, as well as `firstPartyHosts` and http tracking.
=> ✨ Support long tasks and http tracking for attachToExisting

bitrise.yml, packages/datadog_flutter_plugin/android/build.gradle, packages/datadog_flutter_plugin/example/android/app/build.gradle, packages/datadog_flutter_plugin/example/android/app/src/main/kotlin/com/datadoghq/example/flutter/MainActivity.kt, packages/datadog_flutter_plugin/example/android/build.gradle, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, tools/releaser/bin/releaser.dart, tools/releaser/lib/command.dart, tools/releaser/lib/gradle_util.dart, tools/releaser/lib/release_validator.dart, tools/releaser/lib/version_updater.dart
So that we can more quickly iterate on features in the Flutter SDK, we're going to start relying SNAPSHOT builds of the Android SDK instead of only released versions.
As part of the release process, we pin to the last released version of the Android SDK and remove the sonatype snapshot repository from the gradle files.
=> 👷 Support working from Android Snapshot builds

tools/releaser/pubspec.lock, tools/releaser/pubspec.yaml
The Dart Github library added `commits` to their official release. Prior to this I had added it onto a fork. This upgrades us to an official release instead of using my fork.
=> ⬆️ Update github dependency for releaser tool

packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt
The configuration check unit test looked for any log message, which broke when we added a deprecation warning. Now it just checks for warnings from the Flutter plugin.
=> 💚 Fix an underspecified unit test.

packages/datadog_common_test/lib/src/decoders/rum_decoder.dart, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogRumPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ContractHelpers.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogRumPluginTest.kt, packages/datadog_flutter_plugin/example/ios/Podfile.lock, packages/datadog_flutter_plugin/example/ios/Tests/DatadogRumPluginTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/Helpers/ContractHelpers.swift, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_auto_instrumentation_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/auto_integration_scenarios/main.dart, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_method_channel.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_platform_interface.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart, packages/datadog_flutter_plugin/test/rum/ddrum_method_channel_test.dart
Add a configuration option, `reportFlutterPerformance` that uses `SchedulerBinding.addTimingsCallback` to report build and raster times for views. These are sent to Datadog as "performance metrics" for each view.
=> ✨ Add performance metric tracking

packages/datadog_flutter_plugin/e2e_test_app/android/gradle/wrapper/gradle-wrapper.properties
e2e test app is currently failing because it is using an old version of gradle that doesn't support version catalogs.
=> 💚 Upgrade gradle version for e2e test app

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/ios/Classes/DatadogLogsPlugin.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_tracking_http_client/example/integration_test/tracking_http_client_test.dart, packages/datadog_tracking_http_client/example/integration_test/tracking_http_test.dart, packages/datadog_tracking_http_client/example/lib/http/rum_http_instrumentation_third_screen.dart, packages/datadog_tracking_http_client/example/lib/main.dart
If the Datadog internal logger attempted to send a console log while the app was terminating, you would get an assert complaining that the engine had not been run yet. This fixes the issue by restoring `consoleLog` to its initial state during engine detach or app termination.
If we have lots of these callbacks, we should potentially switch the method channel to optional, set it to nil during shutdown, and use optional chaining to avoid the crash.
Fixes #271
=> 🐛 Fix an iOS crash on app termination

packages/datadog_common_test/lib/src/decoders/log_decoder.dart, packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogLogsPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogLogsPluginTest.kt, packages/datadog_flutter_plugin/e2e_test_app/integration_test/logs/logger_test.dart, packages/datadog_flutter_plugin/e2e_test_app/integration_test/test_utils.dart, packages/datadog_flutter_plugin/example/ios/Tests/DatadogConfigurationTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/DatadogLogsPluginTests.swift, packages/datadog_flutter_plugin/integration_test_app/integration_test/logging_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/logging_scenario.dart, packages/datadog_flutter_plugin/ios/Classes/DatadogFlutterModels.swift, packages/datadog_flutter_plugin/ios/Classes/DatadogLogsPlugin.swift, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/src/logs/ddlogs.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs_method_channel.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs_platform_interface.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs_web.dart, packages/datadog_flutter_plugin/test/logs/ddlogs_method_channel_test.dart, packages/datadog_flutter_plugin/test/logs/ddlogs_test.dart
Add parameters to add error information on Logs
This is a minor breaking change, as the `attributes` parameter is now a named arg, to make room for the error parameters (`errorKind`, `errorMessage`, and `errorStack`)
This fixes #264
=> ✨ 🔥 Add the ability to report errors on logs.

packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt
Some properties were moved into the SdkCore / CoreFeature objects, which the unit tests access to make sure they're sending the right data. Use `stop` instead of `flushAndShutdownExectutors` in unit tests (still needed for Integration tests).
=> 💚 Fix android unit tests with v2 changes

packages/datadog_flutter_plugin/e2e_test_app/android/app/build.gradle
Dev snapshots still have an extra configuration property. We need to ignore them in order to run correctly on Android.
=> 💚 Fix e2e tests by ignoring dev snapshots on android

packages/datadog_common_test/lib/src/decoders/rum_decoder.dart, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogFlutterConfiguration.kt, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/example/ios/Tests/DatadogSdkPluginTests.swift, packages/datadog_flutter_plugin/integration_test_app/integration_test/common.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/configuration_telemetry_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/auto_integration_scenarios/main.dart, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin_web.dart, packages/datadog_flutter_plugin/lib/datadog_internal.dart, packages/datadog_flutter_plugin/lib/src/datadog_sdk_method_channel.dart, packages/datadog_flutter_plugin/lib/src/datadog_sdk_platform_interface.dart, packages/datadog_flutter_plugin/lib/src/rum/navigation_observer.dart, packages/datadog_flutter_plugin/lib/src/rum/rum_gesture_detector.dart, packages/datadog_flutter_plugin/test/datadog_sdk_method_channel_test.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_flutter_plugin/test/rum/navigation_observer_test.dart, packages/datadog_tracking_http_client/lib/src/tracking_http.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client_plugin.dart, packages/datadog_tracking_http_client/pubspec.yaml, packages/datadog_tracking_http_client/test/datadog_tracking_client_test.dart, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
Adds methods to modify native configuration telemetry with Flutter specific telemetry
Each Flutter assignable property that is late initialized is tracked in an internal struct and updated as we learn more from the use of the SDK.  When the telemetry is sent, the mapper function transfers all of the known properties over to the telemetry configuration object.
=> 📈 Add configuration telemetry with Flutter specific properties.

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart
Because we currently use runZonedGuarded to catch errors, we need to make sure WidgetsFlutterBinding.ensureInitialized is called inside runZonedGuarded.
This is an issue if you try to set sdkVerbosity (which requires the binding be initialized) before calling DatadogSdk.runApp. This fixes the issue by not calling into the platform channel until Datadog is initialized or during the initialization process.
=> 🐛 Allow sdkVerbosity to be set prior to WidgetsFlutterBinding being initialized

CONTRIBUTING.md, bitrise.yml, full_clean.sh, prepare.sh
The prepare script runs `flutter pub get` in all of the sub-packages, generates `.env` files, and runs code generation is any sub-packages that need it.
=> 👷 Create a ./prepare.sh script

packages/datadog_flutter_plugin/android/build.gradle
jitpack.io (which is backed by JCenter) is not quite stable lately with long downtimes, so let's use lookup in this repo only for dependencies which are in this repo. Since only test dependency is currently using it, it will prevent breaking the build of dependent projects which are building this one from the sources (like Shopist Flutter).
=> Use JitPack only for specific dependencies

packages/datadog_tracking_http_client/CHANGELOG.md, tools/releaser/lib/version_updater.dart
Release of 1.0.1 was missed in the change log on develop. 
Also fix the deployment script to not add "Unreleased" back into the CHANGELOG until we request to bump for the next version (that keeps it out of the released CHANGELOG)
=> 📝 Fix missing version in CHNAGELOG for tracking_http_client

packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/datadog_internal.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_grpc_interceptor/lib/src/datadog_grpc_interceptor.dart, packages/datadog_grpc_interceptor/test/datadog_grpc_interceptor_test.dart, packages/datadog_tracking_http_client/lib/datadog_tracking_http_client.dart, packages/datadog_tracking_http_client/lib/src/tracking_http.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client_plugin.dart, packages/datadog_tracking_http_client/test/datadog_tracking_client_test.dart, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
Instead of setting header types on each client, now we set them as part of `firstPartyHosts` during configuration.  This allows users to set different header types per host.
One oddity is when there are multiple matches, the code merges the two header requests and adds both. For example if you set:
```dart
firstPartyHostsWithTracingHeaders: {
'host.com': { TracingHeaderType.datadog },
'api.host.com': {TracingHeaderType.b3 },
},
```
Calls to `api.host.com` will have both Datadog and b3 headers injected .
=> ✨ Support tracing header types per-host.

packages/datadog_flutter_plugin/e2e_test_app/ios/Podfile, packages/datadog_flutter_plugin/example/ios/Podfile, packages/datadog_flutter_plugin/integration_test_app/integration_test/configuration_telemetry_test.dart, packages/datadog_flutter_plugin/integration_test_app/ios/Podfile, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/scenario_runner.dart, packages/datadog_tracking_http_client/example/ios/Podfile
This pins us to 1.14.0 instead of using latest develop during development. We'll revert this after the next release.
=> 📌 Pinning iOS versions to 1.14.0 temporarily

examples/native-hybrid-app/android/app/build.gradle, packages/datadog_flutter_plugin/android/build.gradle
Pin Android to 1.16.0 for the moment.
=> 📌 Pin Android to 1.16.0

packages/datadog_flutter_plugin/example/android/app/build.gradle, tools/releaser/lib/package_list.dart
I missed a file when pinning Android 1.16.0 (the pinning script was pointing to the wrong file).
This fixes the pin and the pinning script.
=> 🐛 Fix Android pin to 1.16.0

packages/datadog_common_test/pubspec.yaml, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_flutter_plugin/pubspec.yaml
Some users of `datadog_flutter_plugin` are at Flutter 2.8, which is Dart 2.15. In order to continue to support and build on that version we had to downgrade some dev dependencies so we could run tests on Flutter 2.8.
Since Most of the dependencies are dev dependencies and shouldn't affect functionality. The 'lints' package was set to '>= 1.0' as I am okay with always grabbing the most recent version of lints,
=> ⬇️ Downgrade dependencies to Dart 2.15 / Flutter 2.8 levels

tools/releaser/lib/cocoapod_util.dart, tools/releaser/lib/gradle_util.dart
When releasing non-core packages, releaser was removing version information from the core package, which was obviously not correct.
=> 👷 Fix releaser being overzealous with version pinning

packages/datadog_flutter_plugin/integration_test_app/integration_test/logging_mapping_test.dart, packages/datadog_flutter_plugin/test/rum/rum_long_task_observer_test.dart
Occasional telemetry send was breaking the log mapping test. Fix by ignoring non-lists sent to the endpoint.
=> 💚 Fix some flakiness in the log mapping test

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift
Late binding of the consolePrint function on iOS meant that initialization errors weren't seen in the Flutter console, and would only be seen if you were debugging in XCode.
Fixes #328
=> 🐛 Setup `consolePrint` sooner on iOS

bitrise.yml
Bitrise is stalling I think because of something weird going on with not being able to find the junitreport library. We're going to globally install it, as that fixed the issue for previous versions of flutter.
(cherry picked from commit 713eb8c67a202b24fc1405e1fa9fc63885a132ec)
=> 💚 Hopefully fix bitrise stalling.

packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs_web.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart
Web was using an old internal property for version which was replaced with a configuration property.
Fixes #334
=> 🐛 Fix web not properly populating version from config

packages/datadog_flutter_plugin/example/lib/rum_screen.dart, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift
Fix a crash on exit caused by Datadog logging that a view isn't active during an event, which is happening while the app is shutting down and a the Flutter engine, and therefore the method channel for displaying the log, is no longer available.
To fix, we're overriding the method provided by Flutter for de-registering the plugin with the engine on shutdown, but I've yet to see this called in practice.
Fixes #341
This crash is difficult to reproduce, but I have not been able to with this code enabled in many attempts. I added some code to the RUM example to test stopping a view and immediately send an event on `dispose` if one is active, which was able to reproduce the crash fairly consistently, and I have not been able to reproduce.
=> 🐛 Potentially fix crash on exit on iOS

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/example/lib/rum_screen.dart, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_tracking_http_client/example/pubspec.lock, tools/third_party_scanner/pubspec.lock
I'd like to get out the iOS crash fix into the 1.2.x line, so I'm going to cherry pick the fix and hopefully release a point release soon.
=> Cherry pick crash fix into 1.2.x release line

packages/datadog_common_test/lib/src/decoders/rum_decoder.dart, packages/datadog_common_test/lib/src/testing_configuration.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/common.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/configuration_telemetry_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_error_reporting_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_no_auto_instrumentation_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/auto_integration_scenarios/scenario_runner.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/scenario_runner.dart, packages/datadog_flutter_plugin/integration_test_app/lib/main.dart, packages/datadog_flutter_plugin/lib/src/attributes.dart
We now have a configuration option that supports enabling configuration telemetry at 100%, which means I can consistently test it with an integration test. This takes advantage of that new option and re-enables the test.
=> ✅ Re-enable telemetry integration tests

packages/datadog_flutter_plugin/lib/datadog_internal.dart, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
onError in the DatadogTrackingHttpClient was asserting that onError was a `void Function(Object)`, which fails in the assertion if onError is `void Function(dynamic)` (though the `is` test passes in this case).
Fixes #355
=> 🐛 Fix assert on non-standard `onError` function

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart
Because the `originalOnError` will by default call `presentError`, clients were getting duplicate error messages from the double call. Remove the extraneous `presentError`
=> 🐛 Remove extra call to `presentError` in onError callback

packages/datadog_flutter_plugin/lib/datadog_internal.dart, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
Want to do a hotfix on 1.2.x to fix the assert reported in #355.
onError in the DatadogTrackingHttpClient was asserting that onError was a `void Function(Object)`, which fails in the assertion if onError is `void Function(dynamic)` (though the `is` test passes in this case).
=> 🍒 Cherry pick #355 fix to 1.2.x release branch

LICENSE-3rdparty.csv, bitrise.yml, prepare.sh, tools/third_party_scanner/bin/third_party_scanner.dart
Updated the 3rd party license scanner to include the new datadog_webview_tracking package, and ran it to add one new package to the 3rd party list.
=> 👷 Update third party license scanner

bitrise.yml, packages/datadog_webview_tracking/pubspec.yaml, packages/datadog_webview_tracking/test/datadog_webview_tracking_test.dart
Add a very simple method channel test to the webview tracking package, and make sure integration tests are run on CI. Both were missed with the initial merge of the feature.
=> ✅ Add a unit test to webview tracking package

bitrise.yml, examples/native-hybrid-app/flutter_module/pubspec.lock, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt, packages/datadog_flutter_plugin/integration_test_app/integration_test/configuration_telemetry_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_error_reporting_test.dart, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/src/datadog_sdk_method_channel.dart, packages/datadog_flutter_plugin/lib/src/rum/navigation_observer.dart, packages/datadog_flutter_plugin/test/datadog_sdk_method_channel_test.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_webview_tracking/example/integration_test/webview_scenario_test.dart, packages/datadog_webview_tracking/example/ios/Podfile.lock, packages/datadog_webview_tracking/example/lib/main.dart, packages/datadog_webview_tracking/test/datadog_webview_tracking_test.dart, prepare.sh, tools/e2e_generator/pubspec.lock, tools/releaser/pubspec.lock, tools/third_party_scanner/pubspec.lock
We want to add the dartVersion to our configuration telemetry so we can get a better idea of when we can drop support for specific versions of Dart / Flutter (currently we go back to Flutter 2.8).
Also do a little bit of cleanup of some lint warnings.
=> 📈 Add dartVersion to configuration telemetry

packages/datadog_flutter_plugin/lib/src/tracing/tracing_headers.dart, packages/datadog_flutter_plugin/test/tracing/tracing_headers_test.dart
TraceId and SpanId were swapped in both b3 and tracecontext header generation.
Added more unit test coverage for these functions as well.
=> 🐛 Fix b3 and tracecontext header generation

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogRumPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogRumPluginTest.kt, packages/datadog_flutter_plugin/example/.gitignore, packages/datadog_flutter_plugin/example/ios/Tests/DatadogRumPluginTests.swift, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_error_reporting_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/rum_manual_error_reporting_scenario.dart, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/lib/src/rum/ddrum.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_method_channel.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_platform_interface.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart, packages/datadog_flutter_plugin/test/rum/ddrum_method_channel_test.dart
When creating the initial API for RUM I missed adding `errorType` as a parameter on the `addError` methods. This adds that parameter back in.
Fixes #372
=> ✨Add support for `errorKind` on `addError` APIs

packages/datadog_common_test/lib/src/decoders/rum_decoder.dart, packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_test.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart
This sets the `sessionReplaySampleRate` to 0, as Flutter does not support Session Replay, and avoids the Browser SDK reporting the session as a replay session.
=> 🐛 Fix Flutter Web initialization to disable session replay

packages/datadog_flutter_plugin/example/pubspec.yaml, packages/datadog_flutter_plugin/lib/src/rum/rum_user_action_detector.dart
Modify some code that allows datadog_flutter_plugin to continue to support Flutter 2.8.
Downgrade lints to any version above 1.0, and remove generic parameter on HitTest (this generic parameter is marked as optional in later versions of Flutter and 3.0+ are able to omit it without issue)
=> 🧹 Modify code to support Flutter 2.8

packages/datadog_flutter_plugin/integration_test_app/integration_test/logging_mapping_test.dart, packages/datadog_flutter_plugin/integration_test_app/integration_test/logging_test.dart
Some telemetry is getting through (probably when it's sent on its own) and causing certain tests to flake. This sets the sample rate for telemetry on log tests to 0, which should prevent further flakeyness.
=> 💚 Stop sending telemetry on log tests

packages/datadog_flutter_plugin/README.md
The lack of a space at the end of the document before the links was causing all the links to render incorrectly.
Fix a few other formatting issues at the same time.
=> 📝 Fix link rendering in main readme

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogRumPlugin.kt, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogRumPluginTest.kt, packages/datadog_flutter_plugin/example/ios/Tests/DatadogRumPluginTests.swift, packages/datadog_flutter_plugin/example/ios/Tests/Helpers/ContractHelpers.swift, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_kiosk_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/integration_scenarios_screen.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/kiosk_integration_scenario.dart, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/ios/Classes/DatadogRumPlugin.swift, packages/datadog_flutter_plugin/lib/src/rum/ddrum.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_method_channel.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_platform_interface.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart, packages/datadog_flutter_plugin/test/rum/ddrum_method_channel_test.dart, packages/datadog_tracking_http_client/example/pubspec.lock
RUM sessions can be stopped with a call to DdRum.stopSession. This set the current session as inactive and start a new session the next time `startView`, `addUserAction`, or `startUserAction` is called.
Fixes #147
=> ✨ Add the ability to stop sessions

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/integration_test_app/integration_test/rum_manual_error_reporting_test.dart, packages/datadog_flutter_plugin/integration_test_app/lib/integration_scenarios/rum_manual_error_reporting_scenario.dart, packages/datadog_flutter_plugin/integration_test_app/pubspec.lock, packages/datadog_flutter_plugin/integration_test_app/pubspec.yaml, packages/datadog_flutter_plugin/lib/src/logs/ddlog_event.dart, packages/datadog_flutter_plugin/lib/src/rum/rum_user_action_detector.dart, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_flutter_plugin/pubspec.yaml, packages/datadog_webview_tracking/README.md
Flutter 3.0 has been out for almost a year, and we have a bug related to attempting to support down to Flutter 2.8 (#386) so we're going to limit support to 3.0+ starting with the release of SDK version 1.4.
Additionally fix some deprecation warnings that were waiting on an update to Flutter 3 and other documentation issues.
=> ⬆️ Raise minimum supported version to Flutter 3.0+

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/ios/Classes/SwiftDatadogSdkPlugin.swift, packages/datadog_flutter_plugin/pubspec.yaml
The fix we thought we applied in 1.2.2 (#348) didn't seem to work, so we're trying a different approach.
`detachFromEngine` still isn't being called when its supposed to, but `applicationWillTerminate` is being called, and its currently safe to detach twice even if `detachFromEngine` does get called. This should avoid crashes with the console logger attempting to call back to Flutter after its shut down.
Fixes #390
=> 🐛 Fix crash on exit on iOS

packages/datadog_flutter_plugin/CHANGELOG.md
Update the change log with updates to iOS / Android SDK versions and the move of the iOS crash fix into 1.3.3.
=> 📝 Update CHANGELOG

tools/releaser/lib/gradle_util.dart, tools/releaser/lib/package_list.dart, tools/releaser/lib/version_updater.dart
When we release a the Dart package, we can't refer to files outside of the package. The `apply from` that ignores SR snapshots uses a file outside the package and can cause build failures, so it needs to be removed during the release process
=> 👷 Fix releaser to remove bad `apply from`

bitrise.yml
We're having nightly tests fail about 50% of the time complaining that an iOS simulator isn't started. Bitrise has asked that we add a `flutter doctor` call so they can help diagnose.
=> 🔊 Add flutter doctor to diagnose bitrise issue

packages/datadog_flutter_plugin/lib/src/helpers.dart, packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/test/datadog_tracking_http_client_test.dart
Dart has "rethrow" within catch blocks to preserve stack traces, and Futures will preserve stack traces if you "throw" the same exception so long as it is not inside an `async` block. The `close` method had its `onError` marked as async by accident, so it was not preserving the stack trace properly.
Fixes RUMM-3264
=> 🐛 Fix rethrown exceptions not properly preserving stacktrace

packages/datadog_flutter_plugin/example/lib/main.dart, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart
Flutter 3.1 added `PlatformDispatcher.instane.onError` which could be used to catch errors without using `runZonedGuarded`, however there was a bug with Flutter Web with this method that was fixed in Flutter 3.3.
I've replaced the `runZonedGuarded` code with `PlatformDispatcher` and upped the minimum version required for the SDK to 3.3.
I've also changed the example to use `runApp` by default, as it no longer needs to be careful about when it calls `WidgetFlutterBinding.ensureInitialized`
Fixes #416
=> ✨ Use PlatformDispatcher.instance.onError over runZonedGuarded

LICENSE-3rdparty.csv, generate_env.sh, packages/datadog_flutter_plugin/e2e_test_app/lib/main.dart, packages/datadog_flutter_plugin/e2e_test_app/pubspec.yaml, packages/datadog_flutter_plugin/example/lib/crash_reporting_screen.dart, packages/datadog_flutter_plugin/example/lib/logging_screen.dart, packages/datadog_flutter_plugin/example/lib/main.dart, packages/datadog_flutter_plugin/example/lib/rum_screen.dart, packages/datadog_flutter_plugin/example/pubspec.yaml, packages/datadog_flutter_plugin/integration_test_app/pubspec.yaml, packages/datadog_flutter_plugin/lib/src/logs/ddlog_event.dart, packages/datadog_flutter_plugin/pubspec.lock, packages/datadog_flutter_plugin/test/datadog_sdk_method_channel_test.dart, packages/datadog_flutter_plugin/test/logs/ddlogs_method_channel_test.dart, packages/datadog_flutter_plugin/test/rum/ddrum_method_channel_test.dart, packages/datadog_webview_tracking/test/datadog_webview_tracking_test.dart
Updating the minimum version to 3.3+ allows us to lean up some deprecated members (as well as some that will be deprecated in 3.10+).
=> 🧹 Cleanup deprecated members from update to 3.3+

packages/datadog_flutter_plugin/README.md, packages/datadog_flutter_plugin/lib/src/rum/navigation_observer.dart
Realized `viewInfoExtractor` takes the place of the native `viewPredicate`s, it just was poorly documented. Adding new documentation to the repo.
=> 📝 Better documentation for viewInfoExtractor

examples/native-hybrid-app/android/app/build.gradle, packages/datadog_flutter_plugin/android/build.gradle, packages/datadog_flutter_plugin/example/android/app/build.gradle, packages/datadog_webview_tracking/android/build.gradle, tools/releaser/lib/package_list.dart
Current Android SDK has updated to Kotlin 1.8 which is binary incompatible with what the current Flutter SDK expects. Going to pin to 1.19.0 for now until we can update.
=> 📌 Pin Android to 1.19.0 to avoid Kotlin update.

packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/README.md, packages/datadog_tracking_http_client/lib/datadog_tracking_http_client.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart, packages/datadog_tracking_http_client/lib/src/tracking_http_client_plugin.dart
The `DatadogTrackingHttpClient` sets `HttpOverrides.global` without checking if client code has already overridden it. This can lead to unexpected behavior when clients need to use `HttpOverrides`.
I've also added more documentation to the library to make it clear what's happening.
See #424
=> 👩‍💻 Use already provided HttpOverrides when available

packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/pubspec.yaml
Update versions from release of datadog_tracking_http_client 1.3.0
=> 🔀 Update versions from release of datadog_tracking_http_client 1.3.0

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/lib/src/version.dart, packages/datadog_flutter_plugin/pubspec.yaml
Update version numbers from release of datadog_flutter_plugin 1.5.0
=> 🔀 Update versions from datadog_flutter_plugin 1.5.0 release

packages/datadog_tracking_http_client/lib/datadog_tracking_http_client.dart
This pr adds an export for `DatadogTrackingHttpClientListener` so that it can be implemented by consuming applications
=> fix: adding export for DatadogTrackingHttpClientListener

packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/pubspec.yaml
Update for changes related to the datadog_tracking_http_client 1.3.1 release
=> Update for tracking_http_client 1.3.1 release

packages/datadog_flutter_plugin/lib/src/rum/ddrum_events.dart
Two issues show up in telemetry related to mappers, one is a null value in RumCellular, the other is related to using `logger` as a source.
This allows RumCellular members to be null, and switches mappers to use an internal Source enum which allows  `logger` as a possible source, as well as some other missing sources.
=> 🐛 Fix minor issues affecting mappers

packages/datadog_flutter_plugin/e2e_test_app/integration_test/rum/rum_monitor_test.dart
Query for one of the monitors was wrong, and another wasn't sending the method name properly to the action (it was sent to the view).
The bad monitor query was corrected manually instead of re-running the e2e generator.
=> 💚 Minor changes to fix e2e tests

examples/native-hybrid-app/README.md
Applications that add Flutter and the datadog_flutter_plugin with already existing instances of the Datadog SDK for iOS generate build time errors when using two of the options for embedding. This documents that those methods are not supported.
refs: #443
=> 📝 Add caveat for Hybrid applications

packages/datadog_flutter_plugin/e2e_test_app/ios/Podfile, packages/datadog_flutter_plugin/example/ios/Podfile, packages/datadog_flutter_plugin/integration_test_app/ios/Podfile, packages/datadog_tracking_http_client/example/ios/Podfile, packages/datadog_webview_tracking/example/ios/Podfile
Using latest from develop now pulls in 2.0, which the Flutter SDK isn't ready for. Pinning to the last version of 1.x until we're ready to update.
=> 📌 Pin iOS native version to last 1.x version

packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/src/datadog_noop_platform.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs_noop_platform.dart, packages/datadog_flutter_plugin/lib/src/rum/ddrum_noop_platform.dart
When performing widget tests in headless environments (without an emulator, simulator, or real device) There's not "platform" implementation for the DatadogSdk to work with, and it will throw a `MissingPluginException`.
This change gives us a "NoOp" platform which we can use to essentially disable Datadog's functionality for headless tests.
refs: RUMM-3370 #446
=> ✨ Add method to disable Datadog platform operations

packages/datadog_tracking_http_client/CHANGELOG.md, packages/datadog_tracking_http_client/pubspec.yaml
Updates the version numbers for next potential release of datadog_tracking_http_client.
=> 🚀 Update from release of datadog_tracking_http_client 1.4.0

packages/datadog_flutter_plugin/CHANGELOG.md, packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogConfigurationTest.kt, packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart, packages/datadog_flutter_plugin/lib/src/datadog_configuration.dart, packages/datadog_flutter_plugin/lib/src/logs/ddlogs.dart, packages/datadog_flutter_plugin/lib/src/sampler.dart, packages/datadog_flutter_plugin/test/datadog_sdk_test.dart, packages/datadog_flutter_plugin/test/logs/ddlogs_test.dart, packages/datadog_tracking_http_client/example/pubspec.lock, packages/datadog_webview_tracking/example/pubspec.lock
There was a request to add `sampleRate` to Flutter loggers, similar to those that exist on Web and Native. Because of platform differences, Flutter handles log sampling itself, and keeps the sampling rate at the native level at 100%
This also differs slightly from Web, as each log is sampled, instead of each session.
refs: RUMM-3467
=> ✨ Add log sample rate to loggers.
